### ISSUE TITLE
Use miliseconds in metrics

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#1069]
**Describe the desired outcome from the user's perspective**
As an observability admin, I need metrics to be in a common unit.

**Acceptance criteria**
 - export time based metrics in milliseconds that are accurate down to the nanosecond decimal place

**Comment by jfallows** [comment]
@attilakreiner this is needed to eliminate the last divergence for our [opentelemetry-demo](https://github.com/aklivity/opentelemetry-demo) fork.
