### ISSUE TITLE
Implement `zilla dump` command similar to `tcpdump`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#114]
The Zilla runtime has a a pluggable command structure, currently used for `start` and `stop`.

```
./zilla
usage: zilla <command> [ <args> ]

Commands are:
    help    Display help information
    start   Start engine
    stop    Stop engine

See 'zilla help <command>' for more information on a specific command.
```

Add a new `zilla dump` command to produce a virtual packet capture of Zilla shared memory streams that can be dissected in Wireshark as `tcp`, `tls`, `http`, `mqtt`, `amqp`, etc.

Capturing the raw byte stream for each binding in `zilla.json` in [`.pcap format`][pcap-format] is sufficient to let Wireshark dissectors present the structured form of the protocol frames.

[pcap-format]: https://datatracker.ietf.org/doc/html/draft-gharris-opsawg-pcap-02

**Comment by bmaidics** [comment]
I'd like to take this one
