### ISSUE TITLE
Support `risingwave` `pgsql` message transformations

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#1208]
See #1057 discussion for mapping design specifics.

Splitting from #1057 as `pgsql` binding is generic, whereas `risingwave` message transformations over `pgsql` are specific to Risingwave.

 - [x] Support `CREATE TABLE` transformation https://github.com/aklivity/zilla/pull/1211
 - [x] Support `CREATE TABLE` with `PRIMARY KEY` transformation https://github.com/aklivity/zilla/pull/1211
 - [x] Support `CREATE STREAM` transformation 
 - [x] Support `CREATE MATERIALIZED VIEW` transformation https://github.com/aklivity/zilla/pull/1211
 - [x]  Support ALTER STREAM and ALTER TABLE transformation https://github.com/aklivity/zilla/pull/1320
 - [x] Support `DROP TABLE`, `DROP STREAM` and  `DROP MATERIALIZED VIEW`  transformation  https://github.com/aklivity/zilla/pull/1266

**Comment by akrambek** [comment]
There is one task left and I have made good progress but not quite there yet and also will require some end to end testing.

**Comment by rupurt** [comment]
Love the work on this @akrambek :pray:. It would be awesome if we could also support [Feldera](https://github.com/feldera/feldera)
