### ISSUE TITLE
Watch `zilla` configuration for changes and apply automatically

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#138]
After `zilla` is configured and running successfully, support ability to change `zilla.yaml` and have `zilla` notice to apply the changes.

Typically this will involve tearing down an existing configuration `namespace`, and applying the new configuration `namespace`. This requires tearing down any existing streams for bindings in the old `namespace` before applying the new `namespace` configuration.

Note that the new `zilla.yaml` contents may be invalid syntax, and should then be ignored but with a suitable error message to indicate that the attempted configuration changes were unsuccessful, so that the failure can be detected in the logs.

**Comment by bmaidics** [comment]
Edit config file using kubectl:
kubectl edit configmap zilla -n <kubernetes namespace>
