### ISSUE TITLE
Generic helm chart

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#242]
Implement a general purpose helm chart for zilla, such that it can be reused by our zilla-examples, but without any special knowledge of how the zilla-examples work.

Verify the helm chart works for zilla-examples.

Automatically publish to ArtifactHub in reaction to a new zilla git flow release to main branch, via GitHub Actions.

Update zilla-examples to use deployed helm chart from ArtifactHub.

**Comment by joelmsanto** [comment]
Hi team, 

the helm repo is down: oci://ghcr.io/aklivity/charts/zilla

Could you please provide any suggestion how to install Zilla with helm?
