### ISSUE TITLE
Support tombstone messages via sse-kafka binding

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#25]
Kafka `tombstone` messages have a value of `null`.

Per [`HTML5` `SSE` specification](https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream), events with `id` field only and no `data` field would not be dispatched by browsers, instead they would just update the local `last-event-id` to be used in future during `SSE` stream reconnect.

> 1. Set the [last event ID string](https://html.spec.whatwg.org/multipage/server-sent-events.html#concept-event-stream-last-event-id) of the event source to the value of the last event ID buffer. The buffer does not get reset, so the [last event ID string](https://html.spec.whatwg.org/multipage/server-sent-events.html#concept-event-stream-last-event-id) of the event source remains set to this value until the next time it is set by the server.
> 2. If the data buffer is an empty string, set the data buffer and the event type buffer to the empty string and return.

Therefore, we need to represent `tombstone` messages using a different `SSE` event type, such as `delete`, with a non-empty `data` field, as well as an `id` field to advance `last-event-id` in the same way for `tombstone` messages as for non-null messages.

This allows UX list based on SSE stream of Kafka snapshots to be kept in sync based on `SSE` events arriving at the client, with `message` type `SSE` events representing `upserts` and `delete` type `SSE` events representing `tombstones`.

**Comment by akrambek** [comment]
Yeah, that makes sense so that the UX list can be updated on deleted tasks.
