### ISSUE TITLE
Generate `zilla.yaml` from `AsyncAPI` specification

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#256]
Generate `zilla.yaml` from a corresponding `AsyncAPI` definition.

See the [AsyncAPI specification 3.0.0 (Pre-release)](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.3)

Note: we may need additional information beyond `AsyncAPI` definition to be able to fully populate the generated `zilla.yaml`.

**Comment by aDaemonThread** [comment]
[AsyncAPI specification 3.0.0 (Pre-release)](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.12)
