### ISSUE TITLE
Support etag in event id field for sse-kafka binding

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#26]
`http-kafka` binding uses `etag` to support conditional operations, such as `GET if-none-match` or `PUT if-match`.

When clients use both `http-kafka` binding and `sse-kafka` binding in combination, we need to expose the `etag` header of each `kafka` message on each `SSE` event, so that it can be used by the client for `PUT if-match` to support optimistic locking.

The `[progress]/[etag header]` format used for `etag` `http` header in `http-kafka` binding can also be used for the `id` field of each `SSE` event in `sse-kafka` binding to make them compatible.

**Comment by akrambek** [comment]
Makes sense.
