### ISSUE TITLE
Update image base

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#291]
**Describe the bug**
The artifacthub image scanner is detecting vulnerabilities

**To Reproduce**
[open the report on artifacthub](https://artifacthub.io/packages/helm/zilla/zilla?modal=security-report)

**Screenshots**
![image](https://github.com/aklivity/zilla/assets/3012311/25dac1ed-6c7a-4fb7-9dff-cf53ca1d6760)

**Comment by jfallows** [comment]
We pick up the latest `alpine` release as the base image for `zilla` docker image on each `zilla` release, currently `alpine` version `3.18`.

`alpine` version `3.18.2` is now [available](https://hub.docker.com/_/alpine), addressing these issues reported on ArtfactHub, and will be picked up automatically during the next release.
