### ISSUE TITLE
Enhance `tcp` binding to route by `port`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#294]
**Is your feature request related to a problem? Please describe.**
Multiple tcp server bindings in `zilla.yaml` for the same example is confusing, see [zilla-examples](https://github.com/aklivity/zilla-examples).

**Describe the solution you'd like**
Support for `tcp` binding to route by `port` number, so that a single `tcp` `server` can route by port `8080` to `http` and by port `9090` to `tls` for `https` for example.

**Describe alternatives you've considered**
The current approach of multiple `tcp` `server` bindings, one per distinct port, works but is confusing.

**Additional context**
This will simplify the visualization in [Zilla VS Code Extension](https://marketplace.visualstudio.com/items?itemName=aklivity.zilla-vscode-ext).

**Comment by lukefallows** [comment]
I would like to take a go at this issue.
