### ISSUE TITLE
Design observable logs configuration syntax

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#296]
As with other first class concepts in `zilla.yaml`, such as `vaults` and `guards`, we need a general concept of `logs`, independent of how they are stored locally or transmitted remotely, with more specific implementation for observability standards such as [OpenTelemetry](https://opentelemetry.io/).

This can be used to detect Zilla internal errors triggered by external system inconsistencies, such as
 - TCP server name not found (DNS)
 - Kafka broker unreachable (network)
 - Kafka topic name mismatch
 - Kafka topic permissions
 - Kafka topic message key required
 - etc

**Comment by vordimous** [comment]
fixed by https://github.com/aklivity/zilla/pull/839
