### ISSUE TITLE
gRPC method call doesn't respond when status code is not OK

### ISSUE THREAD

**Issue by fgarciacode** [aklivity/zilla#504]
**Describe the bug**
I have a custom gRPC service, the response of its methods sometimes return status codes different to "0 OK" (NotFound, AlreadyExists, PermissionDenied, Unauthenticated). Zilla doesn't respond when the status code of my gRPC is different to "0 OK".

**To Reproduce**
1. Checkout https://github.com/fgarcia-code/examples/tree/main/zilla/echo and start.
2. Use Postman to call the gRPC EchoStatus service with status "OK":
   <img width="1202" alt="image" src="https://github.com/aklivity/zilla/assets/18584151/e53671a4-ccf2-4c01-8edb-c86cc60afe9c">
3. Call with status "Not Found":
   <img width="1202" alt="image" src="https://github.com/aklivity/zilla/assets/18584151/a801944a-ad54-439d-b2cf-5b95bb9f4ac5">
4. Review UI for Apache Kafka, the service publish in `echo-requests`, but not in `echo-responses`.
   <img width="1282" alt="image" src="https://github.com/aklivity/zilla/assets/18584151/23fdca75-c91b-4108-8b8e-e249c438583e">

**Expected behavior**
I think that Zilla should responds in the same way with the status code.

I don't know if I'm doing something wrong.

**Comment by jfallows** [comment]
@fgarcia-code thank you, we'll look into this a post an update.

**Comment by jfallows** [comment]
@fgarcia-code we are testing a fix, please see https://github.com/aklivity/zilla/pull/519.
