### ISSUE TITLE
[DOCS] Fix typos in README file

### ISSUE THREAD

**Issue by singodiyashubham87** [aklivity/zilla#540]
There are some typos in the README file which need to be fixed, Kindly assign me this issue so that I can fix them.

![image](https://github.com/aklivity/zilla/assets/93720428/009be933-8cc9-4462-829d-4b66fce1dd17)

**Comment by jfallows** [comment]
https://www.dictionary.com/browse/clients
https://www.dictionary.com/browse/observability
