### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [aklivity/zilla#545]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/aklivity/zilla/assets/147402107/07ea818e-38e4-4a67-8789-a0065eec938f)

**Comment by Kalyanimhala** [comment]
@jfallows Kindly assign me this issue, I want to work on it. Thank You!

**Comment by jfallows** [comment]
@Kalyanimhala thanks, assigned to you now. 👍

**Comment by Kalyanimhala** [comment]
@jfallows , If you don't mind can I upgrade the Project by adding CONTRIBUTING.md file.
- Importance of CONTRIBUTING.md 
A "Contributing.md" file is added to a repository to provide guidelines and 
instructions for potential contributors on how to collaborate effectively with the project. 
It typically includes information on coding standards, how to submit changes, reporting issues,
 and other important details to streamline the contribution process and maintain a healthy 
open-source community.

**Comment by jfallows** [comment]
@Kalyanimhala we already have a CONTRIBUTING.md at the standard location.
https://github.com/aklivity/zilla/blob/develop/.github/CONTRIBUTING.md
