### ISSUE TITLE
Schema validation fails before the `${{env.*}}` parameters have been removed

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#583]
**Describe the bug**
the json schema does not check for the presence of env variables `${{env.*}}` in the zilla.yaml and invalidates fields that aren't expecting strings. 

**To Reproduce**
1. open a zilla.yaml in vscode with `${{env.*}}` defined in a number field and it will have an error shown

**Comment by jfallows** [comment]
We need to programmatically annotate the `zilla` schema to explicitly support `${...}` expression strings for all object property values, whether `string` or not, and check this schema first on the input config text.

We should also show this annotated schema when verbose schema config is set, so we can output it and use it for VS Code.

Then we should validate using the original (non-annotated) schema after replacing the `${env...}` expressions with environment variable values, to make sure the replaced values still honor the schema.
