### ISSUE TITLE
Support `grpc` custom metadata pass through

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#730]
**Describe the desired outcome from the user's perspective**
As a gRPC service developer, I want the custom metadata added by both the client and server to be made available as it was defined for each other.

**Acceptance criteria**
 - Metadata included in a request from a gRPC client should be visible to the gRPC service that receives the request
 - Metadata included in a response from a gRPC service should be visible to the gRPC client that receives the response

Note: this applies to both `grpc`-`grpc` proxying and `grpc`-`grpc-kafka`-`kafka-grpc`-`grpc` proxying.

**Comment by hedhyw** [comment]
Hello, any updates on this story? Thank you!

**Comment by jfallows** [comment]
@hedhyw do you still need generic metadata headers to propagate or just custom status description per #988 for now?

**Comment by hedhyw** [comment]
> @hedhyw do you still need generic metadata headers to propagate or just custom status description per #988 for now?

generic metadata is required too, thank you!
