### ISSUE TITLE
Question: how does zilla work

### ISSUE THREAD

**Issue by evolvednight** [aklivity/zilla#83]
I see that it's a event driven gateway.

Question is that can we take this and deploy my own instance?  Does zilla instance connect to any external endpoints?  Then publish the message to the kafka topic/kafka server?  Or is every message store in zilla instance?

**Comment by jfallows** [comment]
@evolvednight thanks for your questions!

Yes, we provide `zilla` as a docker image with sample usage in the [`zilla-examples`](https://github.com/aklivity/zilla-examples) repository. You will find a number of different use cases there, highlighting different capabilities of `zilla` with step by step instructions in the `README` of each example.

`zilla` instances can also be configured to connect to your own Kafka cluster to produce and fetch messages, explained in the [`Bring your own Kafka`](https://docs.aklivity.io/zilla/get-started/bring-your-own-kafka) get started guide in our online documentation.

Hope this is helpful. Let us know if you need anything clarified further.
