### ISSUE TITLE
Using the `grpc.kafka.proxy` example setup, Zilla will periodically not deliver the message to the gRPC service defined in the `kafka-grpc` binding

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla#881]
**Describe the bug**
I taxi demo the user sends a new taxi hail request through a grpc kafka proxy setup where a remote grpc service is called synchronously. The request kafka topic is recording the request message but the grpc service does not log receiving that message or throw any errors and there is never a "response" message produced on the responses topic.

**To Reproduce**
1. run the taxi-demo
2. Hail taxis
3. At some point the number of messages on the grpc request and response topics won't match indicating Zilla never delivered the request message.
4. The consumer group for the `kafka-grpc` binding is in the "empty" state

**Expected behavior**
Zilla should deliver all messages and reconnect the consumer group if it becomes disconnected.

**Comment by jfallows** [comment]
No longer reproducible.
