### ISSUE TITLE
Support `{{ mustache }}` syntax in zilla.json

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla#91]
Support [{{ mustache }}](https://mustache.github.io/) syntax in zilla.json.

Consider making the root level objects pluggable, with initial support for `env` to provide access to environment variables from the executing shell.

This avoids the need to put any potentially sensitive information directly into the configuration.

For example:
```
...
    "options":
    {
        "sasl":
        {
            "mechanism": "plain",
            "username": "{{env.SASL_USERNAME}}",
            "password": "{{env.SASL_PASSWORD}}"
        }
    }
...
```

Note: initial support for `env` is already implemented, but disabled by default for now.

**Comment by aDaemonThread** [comment]
Hey @jfallows, I would like to give this issue a try. Can you please assign this to me?
